server.port=8081

spring.application.name=auth-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=Him@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
jwt.secret=mySuperSecretKeyForSigningTokens
jwt.expiration=86400000